development:
  adapter: postgresql
  encoding: unicode
  database: alpha_blog
  pool: 5
  timeout: 5000
 
test:
  adapter: postgresql
  encoding: unicode
  database: alpha_blog
  pool: 5
  timeout: 5000e3
